### ISSUE TITLE
Inventory View plugin included with 4.0.0.5's Wiki Lookup button errors out when clicked

### ISSUE THREAD

**Issue by Terramotus** [GenieClient/Genie4#17]
Date and Time:         1/13/2022 7:36:16 PM
Machine Name:          XXXXXXXXXXXXX
Operating System:      Microsoft Windows 10.0.22000 x64
Environment Version:   6.0.1
Genie Version:         4.0.0.5
Genie Build Date:      1/1/0001 12:00:00 AM

Main
An error occurred trying to start process 'https://drservice.info/wiki.ashx?tap=a whimsical kuwinite zuceira embellished with a floral motif' with working directory 'C:\Users\XXXXXX\Dropbox\Genie 4'. The system cannot find the file specified.

System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'https://drservice.info/wiki.ashx?tap=a whimsical kuwinite zuceira embellished with a floral motif' with working directory 'C:\Users\XXXXXX\Dropbox\Genie 4'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at InventoryView.InventoryViewForm.btnWiki_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by jingounchained** [comment]
Unfortunately, this is an incompatibility between the .NET Framework 4 and 6.
What I have done is added in 4.0.0.6 a new command: **#browser** - which cab be used to launch a url in the NET6 fashion.
Someone will need to update InventoryView (not it) to check the version of the host and send "#browser example.url" if it's version 4.
