### ISSUE TITLE
Error: TriggerPrompt on v 4.0.07

### ISSUE THREAD

**Issue by dantiadr** [GenieClient/Genie4#27]
Been popping up a few times a day on v. 4.0.0.7

```
Date and Time:         1/17/2022 1:23:45 PM
Machine Name:          DESKTOP-R1QAAUE
Operating System:      Microsoft Windows 10.0.19043 x64
Environment Version:   6.0.1
Genie Version:         4.0.0.7
Genie Build Date:      1/1/0001 12:00:00 AM

TriggerPrompt
Collection was modified; enumeration operation may not execute.

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.ArrayList.ArrayListEnumeratorSimple.MoveNext()
   at GenieClient.FormMain.Game_EventTriggerPrompt()
```

**Comment by jingounchained** [comment]
I believe I have this fixed. After you've upgraded to 4.0.1.2, let me know if you see this again.

**Comment by jingounchained** [comment]
closing with no further reports
